name: Update View Counters

on:
  schedule:
    # Run every 12 hours at minute 0 (midnight and noon UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  update-views:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Update view counters
      env:
        GOAT_TOKEN: ${{ secrets.GOAT_TOKEN }}
      run: npm run update-views

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code _data/views.json || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if views changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/views.json
        git commit -m "Update view counters - $(date -u +"%Y-%m-%d %H:%M UTC")"
        git push

    - name: Log result
      run: |
        if [ "${{ steps.git-check.outputs.changed }}" == "true" ]; then
          echo "✅ View counters updated and committed"
        else
          echo "ℹ️ No changes in view counters"
        fi